"""MIgração Inicial

Revision ID: 9bb337f99b0e
Revises: 
Create Date: 2024-09-13 07:27:14.499454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb337f99b0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogos',
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('classificacao_etaria', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_jogo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogos')
    # ### end Alembic commands ###
